### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by swarswa** [Grasscutters/lawnmower#3]
How do I use this plug-in

**Comment by alt3ri** [comment]
@memetrollsXD bruh

**Comment by Shichiha** [comment]
you can use it from within Discord (more specifically, in the Grasscutters Discord Channel), it makes a couple of commands.. It's a [Discord Bot](https://docs.statbot.net/docs/guide/bot/)

**Comment by memetrollsXD** [comment]
This isn’t a Grasscutter plugin. It’s the source code for the discord bot that the official community server uses
